//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snake_Keylogger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snake_Keylogger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports System.Windows.Forms
        ///Imports System.Reflection
        ///
        ///&lt;Assembly: AssemblyTitle(&quot;*Title*&quot;)&gt; 
        ///&lt;Assembly: AssemblyDescription(&quot;*Description*&quot;)&gt; 
        ///&lt;Assembly: AssemblyCompany(&quot;*Company*&quot;)&gt; 
        ///&lt;Assembly: AssemblyProduct(&quot;*Product*&quot;)&gt; 
        ///&lt;Assembly: AssemblyCopyright(&quot;*Copyright*&quot;)&gt; 
        ///&apos;&lt;Assembly: AssemblyTrademark(&quot;*Trademark*&quot;)&gt; 
        ///&lt;Assembly: AssemblyVersion(&quot;*version*&quot;)&gt; 
        ///&apos;&lt;Assembly: AssemblyFileVersion(&quot;*fversion*&quot;)&gt; 
        ///
        ///Module X
        ///    Sub Main()
        ///    	MessageBox.Show(&quot;&quot;, &quot;&quot;, MessageBoxButtons.OK, MessageBoxI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssemblyReverser {
            get {
                return ResourceManager.GetString("AssemblyReverser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Confuser_CLI {
            get {
                object obj = ResourceManager.GetObject("Confuser_CLI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Confuser_Core {
            get {
                object obj = ResourceManager.GetObject("Confuser_Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Confuser_DynCipher {
            get {
                object obj = ResourceManager.GetObject("Confuser_DynCipher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Confuser_Protections {
            get {
                object obj = ResourceManager.GetObject("Confuser_Protections", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Confuser_Renamer {
            get {
                object obj = ResourceManager.GetObject("Confuser_Renamer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Confuser_Runtime {
            get {
                object obj = ResourceManager.GetObject("Confuser_Runtime", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dnlib {
            get {
                object obj = ResourceManager.GetObject("dnlib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] e00aaa77b6494fb47b0dfcff5830c88a {
            get {
                object obj = ResourceManager.GetObject("e00aaa77b6494fb47b0dfcff5830c88a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GalaSoft_MvvmLight_Extras_WPF4 {
            get {
                object obj = ResourceManager.GetObject("GalaSoft_MvvmLight_Extras_WPF4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GalaSoft_MvvmLight_WPF4 {
            get {
                object obj = ResourceManager.GetObject("GalaSoft_MvvmLight_WPF4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KoiVM {
            get {
                object obj = ResourceManager.GetObject("KoiVM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KoiVM_Confuser {
            get {
                object obj = ResourceManager.GetObject("KoiVM_Confuser", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KoiVM_Runtime {
            get {
                object obj = ResourceManager.GetObject("KoiVM_Runtime", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Practices_ServiceLocation {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Practices_ServiceLocation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Snake Keylogger After any Build..
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Obfuscar_Console {
            get {
                object obj = ResourceManager.GetObject("Obfuscar_Console", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ookii_Dialogs_Wpf {
            get {
                object obj = ResourceManager.GetObject("Ookii_Dialogs_Wpf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Res {
            get {
                object obj = ResourceManager.GetObject("Res", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports System.IO
        ///Imports System.Net
        ///Imports System.Net.Mail
        ///Imports System.Runtime.CompilerServices
        ///Imports System.Runtime.InteropServices
        ///Imports System.Security.Cryptography
        ///Imports System.Text
        ///Imports System.Text.RegularExpressions
        ///Imports System.Xml
        ///Imports Microsoft.VisualBasic.CompilerServices
        ///Imports Microsoft.Win32
        ///Imports System
        ///Imports Microsoft.VisualBasic
        ///Imports System.Diagnostics
        ///Imports System.Windows.Forms
        ///Imports System.Drawing
        ///Imports System.Collections.Generic
        ///Imports Sy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StubOne {
            get {
                return ResourceManager.GetString("StubOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports System.IO
        ///Imports System.Net
        ///Imports System.Net.Mail
        ///Imports System.Runtime.CompilerServices
        ///Imports System.Runtime.InteropServices
        ///Imports System.Security.Cryptography
        ///Imports System.Text
        ///Imports System.Text.RegularExpressions
        ///Imports System.Xml
        ///Imports Microsoft.VisualBasic.CompilerServices
        ///Imports Microsoft.Win32
        ///Imports System
        ///Imports Microsoft.VisualBasic
        ///Imports System.Diagnostics
        ///Imports System.Windows.Forms
        ///Imports System.Drawing
        ///Imports System.Collections.Generic
        ///Imports Sy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StubTwo {
            get {
                return ResourceManager.GetString("StubTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Windows_Interactivity {
            get {
                object obj = ResourceManager.GetObject("System_Windows_Interactivity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Teen {
            get {
                object obj = ResourceManager.GetObject("Teen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TestMN {
            get {
                object obj = ResourceManager.GetObject("TestMN", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
